[package]
name = "mdor-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
dioxus = { workspace = true, features = ["desktop"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
mdor-core = { path = "../../crates/mdor-core" }